# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

engineer = Category.create(name: "ITエンジニア")
designer = Category.create(name: "デザイナー")
business = Category.create(name: "ビジネス")
writer = Category.create(name: "ライター")
creative = Category.create(name: "クリエイティブ")
web = Category.create(name: "WEB制作")
office = Category.create(name: "事務・総務・法務")
skill = Category.create(name: "スキル・資格")
finance = Category.create(name: "金融")
estate = Category.create(name: "建築・不動産")
medical = Category.create(name: "医療・健康")
profession = Category.create(name: "法律・士業")
other = Category.create(name: "その他")

engineer_se = engineer.children.create(name: "SE(システムエンジニア)")
engineer_programer = engineer.children.create(name: "プログラマー")
engineer_programer_smartphone = engineer.children.create(name: "プログラマー(スマートフォン)")
engineer_ios = engineer.children.create(name: "iOSアプリエンジニア")
engineer_android = engineer.children.create(name: "Androidアプリエンジニア")
engineer_itconsultant = engineer.children.create(name: "ITコンサルタント")
engineer_network = engineer.children.create(name: "ネットワークエンジニア")
engineer_server = engineer.children.create(name: "サーバー/インフラエンジニア")
engineer_db = engineer.children.create(name: "データベースエンジニア")
engineer_desktop = engineer.children.create(name: "WEBアプリエンジニア")
engineer_duty = engineer.children.create(name: "業務アプリエンジニア")
engineer_tester = engineer.children.create(name: "テスター")
engineer_pm = engineer.children.create(name: "プロジェクトマネージャー")
engineer_other = engineer.children.create(name: "その他エンジニア")

designer_graphic = designer.children.create(name: "グラフィックデザイナー")
designer_illustrator = designer.children.create(name: "イラストレーター")
designer_web = designer.children.create(name: "ウェブデザイナー")
designer_industory = designer.children.create(name: "工業デザイナー")
designer_editorial = designer.children.create(name: "エディトリアルデザイナー")
designer_product = designer.children.create(name: "プロダクトデザイナー")
designer_dtp = designer.children.create(name: "DTPオペレーター/デザイナー")
designer_creative = designer.children.create(name: "クリエイティブデザイナー")
designer_game = designer.children.create(name: "ゲームデザイナー")
designer_book = designer.children.create(name: "装丁家/ブックデザイナー")
designer_other = designer.children.create(name: "その他デザイナー")

business_ceo = business.children.create(name: "社長")
business_manager = business.children.create(name: "会社役員")
business_entrepreneur = business.children.create(name: "起業家")
business_sale = business.children.create(name: "営業代行")
business_student = business.children.create(name: "学生起業")
business_consultant = business.children.create(name: "コンサルタント")
business_sell = business.children.create(name: "IT営業")
business_web = business.children.create(name: "WEBディレクター/WEBプロデューサー")
business_sem = business.children.create(name: "SEO/SEOコンサルタント")
business_analyze = business.children.create(name: "WEBアナリスト")
business_merchandise = business.children.create(name: "マーチャンダイザー")
business_research = business.children.create(name: "リサーチャー")
business_market = business.children.create(name: "マーケッター")
business_account = business.children.create(name: "会計/財務担当")
business_finance = business.children.create(name: "財務担当")
business_advertise = business.children.create(name: "広告/PR担当")
business_support = business.children.create(name: "サポーター")
business_career = business.children.create(name: "キャリアコンサルタント")

writer_write = writer.children.create(name: "ライター/編集")
writer_copy = writer.children.create(name: "コピーライター")
writer_edit = writer.children.create(name: "編集者")
writer_technic = writer.children.create(name: "テクニカルライター")
writer_translate = writer.children.create(name: "翻訳者")

creative_video = creative.children.create(name: "映像カメラマン/ディレクター")
creative_advertise = creative.children.create(name: "広告/CMプランナー")
creative_advertise = creative.children.create(name: "広告/CMプランナー")
creative_picture = creative.children.create(name: "写真家/カメラマン")
creative_music = creative.children.create(name: "音楽家/作曲家/作詞家")
creative_anime = creative.children.create(name: "漫画家/アニメーター")
creative_interior = creative.children.create(name: "インテリアコーディネーター/デザイナー")
creative_garden = creative.children.create(name: "庭師/ガーデンデザイナー")

web_programer = web.children.create(name: "WEBプログラマー")
web_html = web.children.create(name: "HTMLコーダー/マークアップエンジニア")
web_ui = web.children.create(name: "UI/UXデザイナー")
web_flash = web.children.create(name: "Flashデザイナー")

office_general = office.children.create(name: "一般/営業事務")
office_medical = office.children.create(name: "医療事務")
office_legal = office.children.create(name: "法務")
office_human = office.children.create(name: "人事・総務")

skill_manner = skill.children.create(name: "ビジネススキル/マナー")
skill_pc = skill.children.create(name: "パソコン")
skill_english = skill.children.create(name: "英語講師")
skill_translator = skill.children.create(name: "翻訳家")
skill_interpreter = skill.children.create(name: "通訳者")
skill_puncher = skill.children.create(name: "キーパンチャー")

finance_fp = finance.children.create(name: "ファイナンシャルプランナー")
finance_insurance = finance.children.create(name: "保険")
finance_ifa = finance.children.create(name: "IFA")
finance_stock = finance.children.create(name: "株式投資")
finance_fx = finance.children.create(name: "FX")
finance_currency = finance.children.create(name: "仮想通貨")
finance_invest = finance.children.create(name: "投資")
finance_other = finance.children.create(name: "その他金融")

estate_architect = estate.children.create(name: "建築家")
estate_house = estate.children.create(name: "宅地建物取引主任者")
estate_consultant = estate.children.create(name: "不動産コンサルタント")

medical_doctor = medical.children.create(name: "医師")
medical_psychology = medical.children.create(name: "心理カウンセラー")
medical_tooth = medical.children.create(name: "歯科医師")
medical_acupuncture = medical.children.create(name: "鍼灸師")
medical_medicine = medical.children.create(name: "薬剤師")

profession_lawer = profession.children.create(name: "弁護士")
profession_administrative = profession.children.create(name: "行政書士")
profession_judicial = profession.children.create(name: "司法書士")
profession_socialinsurance = profession.children.create(name: "社会保険労務士")
profession_tax = profession.children.create(name: "税理士")
profession_small = profession.children.create(name: "中小企業診断士")
profession_land = profession.children.create(name: "土地家屋診断士")
profession_public = profession.children.create(name: "公認会計士")
profession_estate = profession.children.create(name: "不動産鑑定士")

other_side = other.children.create(name: "副業")
other_fortune = other.children.create(name: "占い師")
other_counselor = other.children.create(name: "カウンセラー")


User.create!(name:  "管理者アカウント", email: "admin@example.jp", password:  "11111111", password_confirmation: "11111111", sex: "不明", age: "不明", area: "不明", industry: "不明", skill: "不明", performance: "不明", introduce: "不明", project: "不明", want_to_do: "不明", want_to_meet: "不明", join_type: "不明", admin: true, category_id: "3")